config/routes.rb
Rails.application.routes.draw do
  get 'portfolios/new'
	#devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'sign-up'}, controllers: { registrations: 'users/registrations' }
	devise_for :users, skip: [:registrations, :sessions]
	as :user do
		get 'sign_up', to: 'users/registrations#new'
		post 'sign_up', to: 'users/registrations#create'
		get 'sign_in', to: 'devise/sessions#new'
		post 'sign_in', to: 'devise/sessions#create'
		delete 'sign_out', to: 'users/sessions#destroy'
	end
	get 'my_portfolios', to: 'users#show'
	resources :portfolios, only: [:new, :create, :destroy, :show, :index]
	root to: 'portfolios#index'
end

app/views/shared/_information.html.erb
<div class="jumbotron mx-sm-5 p-5">
	<h2>Welcome to the Portfolio Backtester!</h2>

	<p class="text-justify mx-sm-5 mt-5">The Portfolio Backtester takes your stocks and their percentages and initial capital and uses this information to calculate earnings. It therefore allows you to create a portfolio and use historical share price data to see how well it would have done.</p>

	<h6 class="text-justify mx-sm-5 mt-5">Please note that this website is designed for educational purposes only. It is not intended to be investment advice.  Seek a duly licensed professional for investment advice.</h6>

</div>

<div class="container">
	<div class="row">
		<div class="col-12 col-md">
			<h5>Instructions for creating a portfolio</h5>

			<ol class="text-secondary small">
				<li>First, if you haven't done so, <%= link_to "Sign up", sign_up_path %> or <%= link_to "Sign in", sign_in_path %>
				<li>Navigate to the <%= link_to "New Portfolio", new_portfolio_path %> page</li>
				<li>Enter in a name for your portfolio and the amount you would like to invest</li>
				<li>Below that you can enter in the symbols (e.g., aapl or msft) and the portfolio percentage for each stock you want to put into the portfolio.</li>
				<li>The portfolio percentage determines how much of the initial capital to invest in each stock and is presented in decimal form.  E.g., if you have an initial capital of $50000 and you want to invest half of that in aapl, you would enter 0.5 for portfolio percentage.</li>
				<li>Be sure that the total percentage numbers for all of the stocks add up to 1</li>
				<li>Each portfolio can include up to ten different stocks.  If you'd like to have less, simply leave the other entries blank</li>
				<li>There are still a few limitations for the API, so if you enter in a stock that you know is correct but you receive an error, it may be that IEX (the api providing the data) does not have those records yet.</li>
			</ol>
		</div>
		<div class="col-12 col-md">

			<h5>How it works</h5>

			<ol class="small text-secondary">
				<li>The symbols are used to get the stock history from IEX API.</li>
				<li>Since there can be a lot of information being pulled for each stock, please allow up to a couple minutes after submitting the form for the calculations to be made.</li>
				<li>Up to five years of data are pulled for each stock</li>
				<li>Once Portfolio Backtester has all the data (opening prices, adjusted markets, highs, lows, etc), it collects all of the closing prices from each day</li>
				<li>Not every stock has a full five years of data. If that is the case, Portfolio Backtester will cut down each stock into the same time length.  E.g., if one stock has 5 years of data and another has only one year, both stocks are cut down to one year.</li>
				<li>After pulling out the closing values and possibly trimming the length of each stock to make them the same, it will start on the earliest day, use the initial capital you have submitted to "buy shares", then check the price one year later and "sell".  It will then do this starting on the next day and so on for all the data available.</li>
				<li>Once the results of each buy/sell period are calculated, the lowest result, the highest result, and the average result are returned.  This is done for a one year investment period, two year investment period, and three year investment period.</li>
			</ol>
		</div>
		<div class="col-12 col-md">

			<h5>Results</h5>

			<ol class="text-secondary">
				<li>Each portfolio links to its results page</li>
				<li>The results display the initial capital and each stock with the percentage alotment</li>
				<li>Beneath those are the results of the portfolio.  It will show the best, worst, and average results over the period of one, two, and three years of investing.  If sections have no amount listed, it means there were not enough records to calculate those results.</li>
			</ol>
		</div>
	</div>
</div>

app/views/shared/_portfolio.html.erb
<li class="my-sm-0 my-5 border-bottom pl-3"><%= link_to object.name, object %> - average yearly return: <%= ((object.one_year_average / object.initial_capital.to_f) * 100).to_i %>% <span>
<% if object.user == current_user %>
	<%= link_to "- delete", portfolio_path(object), method: :delete, class: "small text-secondary" %>
<% end %>
	</span>
</li>

app/views/shared/_portfolio_list.html.erb
	<div class="row">
		<div class="col"></div>
		<div class="col-8-sm mx-5 portfolios-list">
			<ul>
				<% @portfolios.each do |p| %>
					<%= render 'shared/portfolio', object: p %>
				<% end %>
			</ul>
		</div>
		<div class="col"></div>
	</div>