config/routes.rb
Rails.application.routes.draw do
  get 'portfolios/new'
	#devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'sign-up'}, controllers: { registrations: 'users/registrations' }
	devise_for :users, skip: [:registrations, :sessions]
	as :user do
		get 'sign_up', to: 'users/registrations#new'
		post 'sign_up', to: 'users/registrations#create'
		get 'sign_in', to: 'devise/sessions#new'
		post 'sign_in', to: 'devise/sessions#create'
		delete 'sign_out', to: 'users/sessions#destroy'
	end
	get 'my_portfolios', to: 'users#show'
	resources :portfolios, only: [:new, :create, :destroy, :show, :index]
	root to: 'portfolios#index'
end

app/views/layouts/_footer.html.erb
<p class="mx-5 text-center text-muted small border-top mt-3">Data provided for free by <%= link_to "IEX", "https://iextrading.com/developer" %>. View <%= link_to "IEX's Terms of Use.", "https://iextrading.com/api-exhibit-a/" %></p>

app/views/layouts/_header.html.erb
<header class="bg-secondary">
	<div class="row align-items-end">
		<div class="col order-3 order-sm-1"></div>
		<div class="col-sm-6 order-1 order-sm-2">
			<h1 class="text-center pb-3"><%= link_to "Portfolio Backtester", root_path, class: "text-white" %></h1>
		</div>
		<div class="col-sm col-12 order-2 order-sm-3">
			<div class="dropdown text-sm-right text-center p-4">
				<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					<% if user_signed_in? %>
						<%= render 'layouts/signed_in_header' %>
					<% else %>
						<%= render 'layouts/signed_out_header' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_signed_in_header.html.erb
<%= link_to "sign out", sign_out_path, method: :delete, class: "dropdown-item" %>
<%= link_to "My Portfolios", my_portfolios_path, class: "dropdown-item" %>
<%= link_to "All Portfolios", portfolios_path, class: "dropdown-item" %>
<%= link_to "Make New Portfolio", new_portfolio_path, class: "dropdown-item" %>

app/views/layouts/_signed_out_header.html.erb
<%= link_to "sign in", sign_in_path, class: "dropdown-item" %>
<%= link_to "sign up", sign_up_path, class: "dropdown-item" %>
<%= link_to "All Portfolios", portfolios_path, class: "dropdown-item" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio Backtester</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	 	<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<%= render 'layouts/header' %>
		<% flash.each do |msg_type, msg| %>
			<p class="#{msg-type}"><%= msg %></p>
		<% end %>
    <%= yield %>
		<%= render 'layouts/footer' %>
  </body>
</html>